### ISSUE TITLE
support for surfaces without textures

### ISSUE THREAD

**Issue by jachym** [melowntech/vts-tools#2]
It would be great, if you could switch off textures in view configuration.

`surfaces.[texture] = []` could be something like `surfaces.[texture] = None`

Same applies for raster free layers

e.g.

```{
    "view": {

        "surfaces": { 
            "ev1": None, 
            "krnov": None }, 

        "freeLayers": { 

            "melown-mapzen-roads":  {
                "style": "johns-own-mapzen-style"
            },

            "melown-mapzen-places": {},

            "seznam-cr-dem": {
                "boundLayers": ["melown-cuzk-cadastral-parcels"]
            } 
        }  
    }
}
```

**Comment by ladislavhorky** [comment]
Surfaces without internal texture (e.g. DTMs) and no assigned bound-layer are now displayed as shaded mesh. For surfaces with internal texture (e.g. city models) there is no plan to accommodate turning off the texture in view. It can be done on frontend if needed. 

The use-case of having lightweight building data is better solved using LOD2 extracted buildings.
