### ISSUE TITLE
Could NOT find Assimp (missing: ASSIMP_LIBRARIES ASSIMP_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by danammeansbear** [melowntech/vts-tools#3]
pc@pc:~/vts-tools/tools$ make -j4
* Building in build
-- Configuring build system on Linux machine
-- Release mode: Compiling with debug symbols by default. To disable set the BUILDSYS_RELEASE_NDEBUG variable.
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/file2cpp/file2cpp as file2cpp
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/sqlite32cpp/sqlite32db as sqlite32db
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/py2cpp/py2pyc as py2pyc
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/pathstrip/pathstrip as pathstrip
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/py-runnable/py-runnable as py-runnable
-- using /home/pc/vts-tools/tools/buildsys/cmake/tools/compile-pyc/compile-pyc as compile-pyc
-- Setting up project <vts-tools>, version <test>.
-- Build type: <Release>.
-- Enabled C++11 for C++ (GNU)
-- Enabled C11 for C (GNU)
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Found OpenMP.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   program_options
--   filesystem
--   system
--   date_time
--   serialization
--   regex
--   chrono
--   iostreams
--   atomic
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Assimp (missing: ASSIMP_LIBRARIES ASSIMP_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  buildsys/cmake/Modules/FindAssimp.cmake:27 (find_package_handle_standard_args)
  CMakeLists.txt:37 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pc/vts-tools/tools/build/CMakeFiles/CMakeOutput.log".
See also "/home/pc/vts-tools/tools/build/CMakeFiles/CMakeError.log".
Makefile:23: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by danammeansbear** [comment]
Outputlog.txt file generates this



Run Build Command:"/usr/bin/make" "cmTC_eb99b/fast"
/usr/bin/make -f CMakeFiles/cmTC_eb99b.dir/build.make CMakeFiles/cmTC_eb99b.dir/build
make[1]: Entering directory '/home/pc/vts-tools/tools/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_eb99b.dir/feature_tests.cxx.o
/usr/bin/c++    -std=c++98 -o CMakeFiles/cmTC_eb99b.dir/feature_tests.cxx.o -c /home/pc/vts-tools/tools/CMakeFiles/feature_tests.cxx
Linking CXX executable cmTC_eb99b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_eb99b.dir/link.txt --verbose=1
/usr/bin/c++       -rdynamic CMakeFiles/cmTC_eb99b.dir/feature_tests.cxx.o  -o cmTC_eb99b 
make[1]: Leaving directory '/home/pc/vts-tools/tools/CMakeFiles/CMakeTmp'


    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:0cxx_alias_templates
    Feature record: CXX_FEATURE:0cxx_alignas
    Feature record: CXX_FEATURE:0cxx_alignof
    Feature record: CXX_FEATURE:0cxx_attributes
    Feature record: CXX_FEATURE:0cxx_attribute_deprecated
    Feature record: CXX_FEATURE:0cxx_auto_type
    Feature record: CXX_FEATURE:0cxx_binary_literals
    Feature record: CXX_FEATURE:0cxx_constexpr
    Feature record: CXX_FEATURE:0cxx_contextual_conversions
    Feature record: CXX_FEATURE:0cxx_decltype
    Feature record: CXX_FEATURE:0cxx_decltype_auto
    Feature record: CXX_FEATURE:0cxx_decltype_incomplete_return_types
    Feature record: CXX_FEATURE:0cxx_default_function_template_args
    Feature record: CXX_FEATURE:0cxx_defaulted_functions
    Feature record: CXX_FEATURE:0cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:0cxx_delegating_constructors
    Feature record: CXX_FEATURE:0cxx_deleted_functions
    Feature record: CXX_FEATURE:0cxx_digit_separators
    Feature record: CXX_FEATURE:0cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:0cxx_explicit_conversions
    Feature record: CXX_FEATURE:0cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:0cxx_extern_templates
    Feature record: CXX_FEATURE:0cxx_final
    Feature record: CXX_FEATURE:0cxx_func_identifier
    Feature record: CXX_FEATURE:0cxx_generalized_initializers
    Feature record: CXX_FEATURE:0cxx_generic_lambdas
    Feature record: CXX_FEATURE:0cxx_inheriting_constructors
    Feature record: CXX_FEATURE:0cxx_inline_namespaces
    Feature record: CXX_FEATURE:0cxx_lambdas
    Feature record: CXX_FEATURE:0cxx_lambda_init_captures
    Feature record: CXX_FEATURE:0cxx_local_type_template_args
    Feature record: CXX_FEATURE:0cxx_long_long_type
    Feature record: CXX_FEATURE:0cxx_noexcept
    Feature record: CXX_FEATURE:0cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:0cxx_nullptr
    Feature record: CXX_FEATURE:0cxx_override
    Feature record: CXX_FEATURE:0cxx_range_for
    Feature record: CXX_FEATURE:0cxx_raw_string_literals
    Feature record: CXX_FEATURE:0cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:0cxx_relaxed_constexpr
    Feature record: CXX_FEATURE:0cxx_return_type_deduction
    Feature record: CXX_FEATURE:0cxx_right_angle_brackets
    Feature record: CXX_FEATURE:0cxx_rvalue_references
    Feature record: CXX_FEATURE:0cxx_sizeof_member
    Feature record: CXX_FEATURE:0cxx_static_assert
    Feature record: CXX_FEATURE:0cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:0cxx_thread_local
    Feature record: CXX_FEATURE:0cxx_trailing_return_types
    Feature record: CXX_FEATURE:0cxx_unicode_literals
    Feature record: CXX_FEATURE:0cxx_uniform_initialization
    Feature record: CXX_FEATURE:0cxx_unrestricted_unions
    Feature record: CXX_FEATURE:0cxx_user_literals
    Feature record: CXX_FEATURE:0cxx_variable_templates
    Feature record: CXX_FEATURE:0cxx_variadic_macros
    Feature record: CXX_FEATURE:0cxx_variadic_templates

**Comment by danammeansbear** [comment]
I also ran this command.

sudo apt-get install -y assimp-utils

**Comment by vaclavblazek** [comment]
The `assimp-utils` package contains command line tools, not developement support. Dbian/Ubuntu's naming scheme for dev packages for library `xyz` is `libxyz-dev`, i.e. `libassimp-dev` in this case.

BTW, VTS tools are in the ubuntu package `vts-tools` available in our repo, no need to build it yourself.

**Comment by danammeansbear** [comment]
So I tried sudo apt-get install vts-tools and got the error

The following packages have unmet dependencies:
 vts-tools : Depends: gdal-abi-2-2-3

so i did sudo apt-get install libgdal120 
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libgdal20_2.2.3+dfsg-2_amd64.deb.html
and that didnt work but what did make the packages install correctly was the solution here https://gis.stackexchange.com/questions/216780/cannot-install-qgis-2-18-from-repository-on-debian-stretch-package-gdal-abi-2/216898
